server-port=25565
online-mode=false
max-players=100
view-distance=8
simulation-distance=6
motd=terminal-minceraft public server
level-seed=3257840388504953787
gamemode=survival
difficulty=normal
pvp=true
spawn-protection=16
enable-command-block=false
white-list=false
enforce-whitelist=false
max-tick-time=60000
network-compression-threshold=256
